version: '2'
services:

  app:
    build:
      context: . 
      dockerfile: Dockerfile
    ports: 
      - "8080"
    networks:
      - service-network
    volumes:
      - .:/vol/development
    depends_on:
      - mariadb

  mariadb:
      image: mariadb:10.0.25
      command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
      ports:
          - "3306"
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_USER: "rust_api"
          MYSQL_PASSWORD: "rust_api"
          MYSQL_DATABASE: "rust_api"
      networks:
          - service-network
networks:
  service-network:
    driver: bridge